"""Chat: ask / history / cancel / retry.

A question becomes a ``chat_messages`` row + an ``answer`` job in ONE transaction. The answer is
generated by the worker, so the result survives the app being backgrounded: the client re-reads
``GET …/messages/{id}``.

Money: nothing is charged at «send». The core charges inside ``GenerationService.run()`` only
when the model delivered; failures and cancellations cost nothing. A request that the policy
refuses is stored as ``blocked`` (the question is kept, nothing queued); after a purchase the
client calls ``retry`` explicitly — access never auto-spends.
"""

from __future__ import annotations

import base64
import uuid

from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.ext.asyncio import AsyncSession

from app.domain import access, jobs
from app.domain.config import DomainSettings
from app.domain.errors import (
    EmptyTextError,
    InvalidStateError,
    LimitExceededError,
    MessageNotFoundError,
)
from app.domain.models import ChatMessage
from app.domain.pricing import KIND_ANSWER
from app.domain.repository import (
    get_message,
    get_topic,
    message_view,
    now,
    resolve_selection,
    touch_topic,
)
from app.domain.schemas import MessagesPage, MessageView


def _encode(seq: int) -> str:
    return base64.urlsafe_b64encode(str(seq).encode()).decode().rstrip("=")


def _decode(cursor: str | None) -> int | None:
    if not cursor:
        return None
    try:
        return int(base64.urlsafe_b64decode(cursor + "=" * (-len(cursor) % 4)).decode())
    except (ValueError, UnicodeDecodeError):
        return None


class ChatService:
    def __init__(self, session: AsyncSession, settings: DomainSettings) -> None:
        self._session = session
        self._settings = settings

    async def ask(
        self,
        user_id: uuid.UUID,
        topic_id: uuid.UUID,
        *,
        question: str,
        source_ids: list[uuid.UUID] | None,
        idempotency_key: str | None,
    ) -> MessageView:
        topic = await get_topic(self._session, user_id, topic_id)
        if idempotency_key:
            existing = await self._session.scalar(
                select(ChatMessage).where(
                    ChatMessage.user_id == user_id, ChatMessage.idempotency_key == idempotency_key
                )
            )
            if existing is not None:
                if existing.topic_id != topic_id:
                    raise MessageNotFoundError("Сообщение не найдено.")
                return await message_view(self._session, existing, replay=True)
        text = question.strip()
        if not text:
            raise EmptyTextError("Вопрос пустой.")
        if len(text) > self._settings.question_max_chars:
            raise LimitExceededError(
                f"Вопрос длиннее {self._settings.question_max_chars} символов."
            )
        selection = await resolve_selection(self._session, user_id, topic_id, source_ids)

        demo_free = (
            topic.is_demo
            and await access.demo_free_left(self._session, user_id, self._settings) > 0
        )
        status, reason = "queued", None
        if not demo_free:
            policy = await access.check(self._session, user_id, KIND_ANSWER)
            reason = access.block_reason(policy)
            status = "blocked" if reason else "queued"

        stmt = (
            insert(ChatMessage)
            .values(
                topic_id=topic_id,
                user_id=user_id,
                question=text,
                status=status,
                block_reason=reason,
                requested_source_ids=selection.source_ids,
                source_version_ids=selection.version_ids,
                answer={"skippedSources": [s.model_dump(mode="json") for s in selection.skipped]},
                is_demo_free=demo_free,
                idempotency_key=idempotency_key,
            )
            .on_conflict_do_nothing(
                index_elements=["user_id", "idempotency_key"],
                index_where=ChatMessage.idempotency_key.isnot(None),
            )
            .returning(ChatMessage.id)
        )
        message_id = await self._session.scalar(stmt)
        if message_id is None:
            existing = await self._session.scalar(
                select(ChatMessage).where(
                    ChatMessage.user_id == user_id, ChatMessage.idempotency_key == idempotency_key
                )
            )
            assert existing is not None
            return await message_view(self._session, existing, replay=True)
        if status == "queued":
            await jobs.enqueue(self._session, kind="answer", ref_id=message_id, user_id=user_id)
        await touch_topic(self._session, topic_id)
        message = await get_message(self._session, user_id, topic_id, message_id)
        return await message_view(self._session, message)

    async def list(
        self, user_id: uuid.UUID, topic_id: uuid.UUID, *, cursor: str | None, limit: int
    ) -> MessagesPage:
        await get_topic(self._session, user_id, topic_id)
        stmt = select(ChatMessage).where(
            ChatMessage.topic_id == topic_id, ChatMessage.user_id == user_id
        )
        before = _decode(cursor)
        if before is not None:
            stmt = stmt.where(ChatMessage.seq < before)
        rows = (
            await self._session.scalars(stmt.order_by(ChatMessage.seq.desc()).limit(limit + 1))
        ).all()
        page = rows[:limit]
        return MessagesPage(
            items=[await message_view(self._session, m) for m in page],
            nextCursor=_encode(page[-1].seq) if len(rows) > limit and page else None,
        )

    async def get(
        self, user_id: uuid.UUID, topic_id: uuid.UUID, message_id: uuid.UUID
    ) -> MessageView:
        await get_topic(self._session, user_id, topic_id)
        message = await get_message(self._session, user_id, topic_id, message_id)
        return await message_view(self._session, message)

    async def cancel(
        self, user_id: uuid.UUID, topic_id: uuid.UUID, message_id: uuid.UUID
    ) -> MessageView:
        await get_topic(self._session, user_id, topic_id)
        message = await get_message(self._session, user_id, topic_id, message_id)
        if message.status not in ("queued", "running"):
            raise InvalidStateError("Ответ уже получен или запрос не выполняется.")
        # queued: the job is dropped. running: the provider sees the flag between model calls and
        # stops with a failure — which the core never charges.
        message.status = "canceled"
        message.completed_at = now()
        message.updated_at = now()
        await jobs.cancel_queued(self._session, kind="answer", ref_id=message.id)
        await self._session.flush()
        return await message_view(self._session, message)

    async def retry(
        self, user_id: uuid.UUID, topic_id: uuid.UUID, message_id: uuid.UUID
    ) -> MessageView:
        """Explicit re-run of a failed / blocked / canceled question.

        The sources are re-resolved NOW: a material deleted or excluded since the original question
        is not used, even though the old message listed it.
        """
        topic = await get_topic(self._session, user_id, topic_id)
        message = await get_message(self._session, user_id, topic_id, message_id)
        if message.status not in ("failed", "blocked", "canceled"):
            raise InvalidStateError("Повторить можно только неудавшийся или отменённый запрос.")
        selection = await resolve_selection(
            self._session, user_id, topic_id, list(message.requested_source_ids)
        )
        demo_free = topic.is_demo and (
            message.is_demo_free
            or await access.demo_free_left(self._session, user_id, self._settings) > 0
        )
        reason = None
        if not demo_free:
            reason = access.block_reason(await access.check(self._session, user_id, KIND_ANSWER))
        message.status = "blocked" if reason else "queued"
        message.block_reason = reason
        message.is_demo_free = demo_free
        message.error_code = None
        message.error_message = None
        message.completed_at = None
        message.attempt = message.attempt + 1
        message.source_version_ids = selection.version_ids
        message.answer = {"skippedSources": [s.model_dump(mode="json") for s in selection.skipped]}
        message.usage = None
        message.updated_at = now()
        await self._session.flush()
        if message.status == "queued":
            await jobs.enqueue(self._session, kind="answer", ref_id=message.id, user_id=user_id)
        return await message_view(self._session, message)
